name: Build and test library app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Use Node.js v18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Run the unit tests
      run: npm run test:unit
    - name: Display softuni UserName
      run: echo "Martinzz3"

  run-ui-tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Use Node.js v18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Install Playwright Browser
      run: npx playwright install
    - name: Start the application
      run: npm run start & 
    - name: Run the UI tests
      run: npm run test:ui
   
  deploy-production:
    runs-on: ubuntu-latest
    needs: run-ui-tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
